### ISSUE TITLE
volumectl cannot unmute

### ISSUE THREAD

**Issue by vandah** [misterdanb/avizo#11]
I can mute sound with `volumectl mute` but then I am not able to unmute it neither with `volumectl  mute` nor with `volumectl unmute` despite the indicator showing that it's unmuting. It can still be unmuted directly with `pactl` as shown bellow at the end.

```
➜  ~ pactl list sinks | grep Mute
	Mute: no
➜  ~ volumectl mute
➜  ~ pactl list sinks | grep Mute
	Mute: yes
➜  ~ volumectl mute
.43
➜  ~ pactl list sinks | grep Mute
	Mute: yes
➜  ~ volumectl unmute
.43
➜  ~ pactl list sinks | grep Mute
	Mute: yes
➜  ~ pactl set-sink-mute $(pactl list short sinks | awk '/RUNNING/{print $1}') no
➜  ~ pactl list sinks | grep Mute
	Mute: no
```

I am running avizo 1.0-1 from AUR.

**Comment by misterdanb** [comment]
Is this still a problem with the newest version of volumectl, which uses pulseaudio cli tools in favor of alsa?

**Comment by vandah** [comment]
likely no, I just tried and it looks like it works okay :+1:
