### ISSUE TITLE
Notification is sometimes not in the center of the screen

### ISSUE THREAD

**Issue by vandah** [misterdanb/avizo#13]
Usually, the notification would appear in the middle of the screen. But sometimes it is moved a bit as seen [here](https://i.imgur.com/aNu5x8t.jpg). The only way I found to fix this was to restart the service. It could probably also be related to a window manager (I use i3wm) or other things but I have not found any direct cause yet.

**Comment by jirutka** [comment]
This has been probably fixed by #19.

**Comment by misterdanb** [comment]
@vandah Is your problem fixed? If so, I would like to close this issue. :)
