### ISSUE TITLE
Cannot build latest version

### ISSUE THREAD

**Issue by mleone87** [misterdanb/avizo#15]
This is what the latest build from AUR, based on the lastest code, shows:

+ exec meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_lto=true -D b_pie=true avizo build
The Meson build system
Version: 0.59.1
Source dir: /home/user/.local/cache/paru/clone/avizo/src/avizo
Build dir: /home/user/.local/cache/paru/clone/avizo/src/build
Build type: native build
Project name: avizo
Project version: 0.0
C compiler for the host machine: ccache cc (gcc 11.1.0 "cc (GCC) 11.1.0")
C linker for the host machine: cc ld.bfd 2.36.1
Vala compiler for the host machine: valac (valac 0.52.5)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency glib-2.0 found: YES 2.68.4
Run-time dependency gtk+-3.0 found: YES 3.24.30
Run-time dependency gobject-2.0 found: YES 2.68.4
Library gtk-layer-shell found: YES
Build targets in project: 4

Found ninja-1.10.2 at /usr/bin/ninja
ninja: Entering directory `build'
[4/9] Compiling Vala source ../avizo/src/avizo_service.vala
FAILED: src/avizo-service.p/avizo_service.c
valac -C --target-glib=2.38 --pkg gobject-2.0 --pkg gtk+-3.0 --pkg glib-2.0 --color=always --directory src/avizo-service.p --basedir ../avizo/src --gresources=../avizo/avizo.gresource.xml --pkg=GtkLayerShell-0.1 ../avizo/src/avizo_service.vala
error: Package `xlib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `cairo-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GModule-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `cairo-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 9 error(s), 0 warning(s)
[5/9] Compiling Vala source ../avizo/src/avizo_client.vala
../avizo/src/avizo_client.vala:66.14-67.73: warning: unhandled error `GLib.IOError'
../avizo/src/avizo_client.vala:153.3-153.22: warning: unhandled error `GLib.DBusError'
		_service.show(_time);
		^^^^^^^^^^^^^^^^^^^^
../avizo/src/avizo_client.vala:153.3-153.22: warning: unhandled error `GLib.IOError'
		_service.show(_time);
		^^^^^^^^^^^^^^^^^^^^
Compilation succeeded - 3 warning(s)
ninja: build stopped: subcommand failed.

Thanks!

**Comment by misterdanb** [comment]
I fear you are missing some gtk/glib packages (or the vapi binding files moved to another package?), which are erroneously not listed in the `PKGBUILD`. Since I cannot reproduce the error, it would be very helpful, if you are able to identify those packages. I'll also have a look again at my installed packages/to which package the files belong.

**Comment by jirutka** [comment]
You need package [gobject-introspection](https://archlinux.org/packages/extra/x86_64/gobject-introspection/).

**Comment by mleone87** [comment]
That was it! Maybe it should be useful to update de PKGBUILD dependencies?
