### ISSUE TITLE
missing in some dependence ?

### ISSUE THREAD

**Issue by mh4nx7net** [misterdanb/avizo#2]
of each gtk app i got some love message

test by vala-panel
=================
vala-panel:24418): Gdk-CRITICAL **: 09:45:38.993: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed

test by volumectl and lightctl
=================
** (avizo-client:24911): CRITICAL **: 09:53:12.070: file ../src/avizo_client.vala: line 151: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.danb.avizo.service was not provided by any .service files (g-dbus-error-quark, 2)

as above , what ive missing ?

**Comment by mh4nx7net** [comment]
just solved by installing gdm/gtk/gnome-package-service-or-else. still try a way for fiting dependence

**Comment by misterdanb** [comment]
I don't understand, what is meant by “test by vala-panel”, what have you tested exactly?
The second part “test by volumectl and lightctl“ should only happen, if you forgot to start the avizo service. If it has a different reason, could you please provide more information on this, too?
