### ISSUE TITLE
lightctl not work correctly

### ISSUE THREAD

**Issue by mh4nx7net** [misterdanb/avizo#3]
![grimshoot-slurp-2019-12-02-03-23-11](https://user-images.githubusercontent.com/33443311/69919782-2921bd80-14b3-11ea-80cc-f3b7b4032236.png)
any else, when i increase or decrease the light, simultaneously the indicator not following. thank for reply

**Comment by misterdanb** [comment]
Can you please elaborate this? More detailed steps to reproduce the bug would be helpful, too!
