### ISSUE TITLE
Styling/config

### ISSUE THREAD

**Issue by properlypurple** [misterdanb/avizo#5]
It would be nice to be able to have a config file, or a css file, to style the window. It looks like gtk, so it should be possible to style using some css.

**Comment by properlypurple** [comment]
I see that avizo-client can take arguments for colors. This can either br implemented by loading a config file from XDG_CONFIG_HOME or by making sure that volumectl and lightctl can take color arguments and pass them to avizo-client.

@misterdanb Which approach would you prefer? I'll do some tinkering and make a PR.

**Comment by misterdanb** [comment]
I think both variants are suitable. Command line arguments have the advantage that you can just place them in line with the bindsym command in your Sway config for example, on the other hand with a configuration file you do not have to store the same color in two player (lightctl and volumectl command).

**Comment by properlypurple** [comment]
Great! I'll try and whip something up this weekend. Thanks!

**Comment by KoalaV2** [comment]
Any update on this? would love to do some styling.

**Comment by jirutka** [comment]
@KoalaV2, I implemented support for configuration file in #21.
