### ISSUE TITLE
border doesnt appear to work

### ISSUE THREAD

**Issue by Keloran** [misterdanb/avizo#58]
here is my config, i am prob being an idiot, but it appears that border-color doesn't work

```
[default]
background = rgb(40, 42, 54)
border-color = rgba(98, 114, 164, 0.8)
bar-fg-color = rgb(189, 147, 249)
border-width = 5
border-radius = 5
```

**Comment by misterdanb** [comment]
Hey, what’s your system? Wayland or X11, which window manager, compositor or desktop environment are you using?

**Comment by Keloran** [comment]
this is on wayland with hyprland

**Comment by arminius-smh** [comment]
Which version are you running? I'm on wayland with hyprland as well and it works on the latest git

Keep in mind that the border-color option was added after the release of 1.2.1

**Comment by Keloran** [comment]
this does work now, I was running 1.2.1
